apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: theport
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: helloworld
  type: LoadBalancer
status:
  loadBalancer: {}